config/routes.rb
Rails.application.routes.draw do

 root to: 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  post 'users' => 'users#create'
  get  'log' => 'welcome#log'
  get 'users/:id' => "users#show", as: 'user_show'
  get 'user_edit/:id' => 'users#edit' , as: 'user_edit'
  patch 'user_update/:id'=> 'users#update', as: 'user_update'
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password

  validates_presence_of :email
  validates_uniqueness_of :email

has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	 if user.present? && user.authenticate(params[:password])
  	 	session[:user_id] = user.id
     # render 'log', :notice =>"Logged IN!!"
     redirect_to log_path
    else
      flash[:notice]= 'invalid credentials'
    	render 'new'
    end
  end

  def destroy
  	session[:user_id] = nil
    redirect_to login_path
  end
  
  
end

app/controllers/users_controller.rb
lass UsersController < ApplicationController
  def new
    @user=User.new
  end

  def create
  	@user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path ,:notice =>"Signed Up!!"
    else
    #  flash[:error]='user creation failed'
      render 'new'
    end
  end

  def edit
    # current_user = User.find(session[:user_id]) if session[:user_id]
  end
   
  def update
  # current_user = User.find(session[:user_id]) if session[:user_id]

  if current_user.update(user_params)
    redirect_to user_show_path(current_user.id)
  else
    render 'edit'
  end
  end

  def show

  end


private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 
 def log
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gif_controller_helper.rb
module GifControllerHelper
end

app/helpers/gif_helper.rb
module GifHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifVault</title>
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="user_nav">

<% if current_user %>
  Signed in as <%=  current_user.name %> | <%= link_to "Logout", logout_path %>
<% else %>
  <%= link_to 'Login', login_path %> | <%= link_to 'Signup', signup_path %>
<% end %>
</div >
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Editing Details</h1>
 
<%= form_for current_user, url: user_update_path(current_user), method: :patch do |f| %>
 
<% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(current_user.errors.count, "error") %> prohibited this user from being saved:
      </h2>
      <ol>
        <% current_user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ol>
    </div>
  <% end %>
  Name: <%=   f.text_field :name %><br />
  Email: <%=  f.text_field :email %><br />
  Password:<%= f.password_field :password %><br />
  Password Confirmation: <%= f.password_field :password_confirmation %><br />
  Image: <%= f.file_field :avatar %><br />
  <p class="button"><%= f.submit %></p>

<% end %>

<%= link_to 'Back', login_path %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for @user, url: users_path, :html => { :multipart => true } do |f| %>
 
 <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
 <% end %>
  Name: <%=   f.text_field :name %><br />
  Email: <%=  f.text_field :email %><br />
  Password:<%= f.password_field :password %><br />
  Password Confirmation: <%= f.password_field :password_confirmation %><br />
  Image: <%= f.file_field :avatar %><br />
  <p class="button"><%= f.submit %></p>

<% end %>

app/views/users/show.html.erb
hello

<br><%= image_tag current_user.avatar.url(:thumb) %> <br>
<% if current_user %>
  Logged in as <%= current_user.name %>
 <% else %>
   invalid current_user
 <% end %>
<%#= image_tag current_user.avatar.url %>
<%#= image_tag current_user.avatar.url(:medium) %>
<p>
  <strong>Name:</strong>
  <%= current_user.name %>
</p>
 
<p>
  <strong>Email Id:</strong>
  <%= current_user.email %>
</p>
<p> 

  <%= link_to 'Edit', user_edit_path(current_user.id) %>
</p>

app/views/welcome/log.html.erb
<br><%= image_tag current_user.avatar.url(:thumb) %> <br>
<% if current_user %>
  Logged in as <%= current_user.name %>
 <% else %>
   invalid current_user
 <% end %>
<%#= image_tag current_user.avatar.url %>
<%#= image_tag current_user.avatar.url(:medium) %>
<p>
  <strong>Name:</strong>
  <%= current_user.name %>
</p>
 
<p>
  <strong>Email Id:</strong>
  <%= current_user.email %>
</p>
<p> 
  <%= link_to 'Back', login_path %>
  <%= link_to 'Edit', user_edit_path(current_user.id) %>
</p>